### ISSUE TITLE
Busy wait for OpenCL

### ISSUE THREAD

**Issue by ddemidov** [bhSPARSE/Benchmark_SpTRSV_using_CSC#1]
Hi,

First of all, this is a very nice idea, thanks for publishing it!

Now, to my question: on p. 6 of the paper you say "Although the lock here is a spin-lock, it does not have the busy-waiting problem. Based on our observation, if the `clock()` function is invoked inside the waiting loop, the hardware warp scheduler will be signalled to switch to the next warp context. This avoids the execution deadlock." This makes sense, but in your OpenCL [implementation of the busy-wait loop](https://github.com/bhSPARSE/Benchmark_SpTRSV_using_CSC/blob/c3a52b766ed6251b34e8c51481ff95defcd88886/SpTRSV_opencl_amd/spts_syncfree_opencl.h#L244) you don't use the trick (obviosly because the `clock()` function is unavailable in OpenCL). Does that mean that the OpenCL version may experience deadlocks? And if not, why the trick was necessary for the CUDA version?

Cheers,
Denis.

**Comment by weifengliu-ssslab** [comment]
Thanks Denis!

The clock() function is used because nvcc compiler tries to remove the `do-while' loop while compiling, if the loop is empty. We actually can do other things here to make the loop (i.e., busy-waiting) functional. In the OpenCL case, compilers does not remove empty`do-while' loop, so nothing coded there.

Any deadlock was not noticed in our experiments, since thread-blocks (or work-groups in OpenCL context) are issued in the ascending order on the tested NV and AMD GPUs, meaning the dependencies are always released before a warp (wavefront) starts its busy-waiting.

Cheers,

Weifeng

**Comment by ddemidov** [comment]
Thanks!
